<?php

namespace edit\blocks;

use pocketmine\block\Block;

class BlockType{

	public static function register(){
		//self::$AIR = new BlockType(Block::AIR, ["Air", "air"]
	}

	public static $shouldPlaceLast = [
		Block::SAPLING,
		Block::BED_BLOCK,
		Block::POWERED_RAIL,
		Block::DETECTOR_RAIL,
		Block::GLASS_PANE,
		Block::DEAD_BUSH,
		Block::PISTONARMCOLLISION,
		Block::YELLOW_FLOWER,
		Block::RED_FLOWER,
		Block::BROWN_MUSHROOM_BLOCK,
		Block::RED_MUSHROOM_BLOCK,
		Block::TORCH,
		Block::FIRE,
		Block::REDSTONE_WIRE,
		Block::WHEAT_BLOCK,
		Block::LADDER,
		Block::RAIL,
		Block::LEVER,
		Block::STONE_PRESSURE_PLATE,
		Block::WOODEN_PRESSURE_PLATE,
		Block::UNLIT_REDSTONE_TORCH,
		Block::LIT_REDSTONE_TORCH,
		Block::STONE_BUTTON,
		Block::SNOW,
		Block::PORTAL,
		Block::UNPOWERED_REPEATER,
		Block::POWERED_REPEATER,
		Block::TRAPDOOR,
		Block::VINE,
		Block::LILY_PAD,
		Block::NETHER_WART_PLANT,
		Block::PISTON,
		Block::STICKY_PISTON,
		Block::COCOA,
		Block::TRIPWIRE_HOOK,
		Block::FLOWER_POT_BLOCK,
		Block::CARROTS,
		Block::POTATOES,
		Block::WOODEN_BUTTON,
		Block::ANVIL,
		Block::LIGHT_WEIGHTED_PRESSURE_PLATE,
		Block::HEAVY_WEIGHTED_PRESSURE_PLATE,
		Block::UNPOWERED_COMPARATOR,
		Block::POWERED_COMPARATOR,
		Block::ACTIVATOR_RAIL,
		Block::IRON_TRAPDOOR,
		Block::CARPET,
		Block::DOUBLE_PLANT,
		Block::DAYLIGHT_DETECTOR_INVERTED
	];

	public static function shouldPlaceLast(int $id) : bool{
		return in_array($id, self::$shouldPlaceLast);
	}

	public static $shouldPlaceFinal = [
		Block::SIGN_POST,
		Block::OAK_DOOR_BLOCK,
		Block::SPRUCE_DOOR_BLOCK,
		Block::BIRCH_DOOR_BLOCK,
		Block::JUNGLE_DOOR_BLOCK,
		Block::ACACIA_DOOR_BLOCK,
		Block::DARK_OAK_DOOR_BLOCK,
		Block::WALL_SIGN,
		Block::IRON_DOOR_BLOCK,
		Block::CACTUS,
		Block::REEDS_BLOCK,
		Block::CAKE_BLOCK,
		Block::PISTONARMCOLLISION,
		Block::STANDING_BANNER,
		Block::WALL_BANNER
	];

	public static function shouldPlaceFinal(int $id) : bool{
		return in_array($id, self::$shouldPlaceFinal);
	}

	public static $canPassThrough = [
		Block::AIR,
		Block::WATER,
		Block::STILL_WATER,
		Block::POWERED_RAIL,
		Block::DETECTOR_RAIL,
		Block::COBWEB,
		Block::GLASS_PANE,
		Block::DEAD_BUSH,
		Block::YELLOW_FLOWER,
		Block::RED_FLOWER,
		Block::BROWN_MUSHROOM_BLOCK,
		Block::RED_MUSHROOM_BLOCK,
		Block::TORCH,
		Block::FIRE,
		Block::REDSTONE_WIRE,
		Block::WHEAT_BLOCK,
		Block::SIGN_POST,
		Block::LADDER,
		Block::RAIL,
		Block::WALL_SIGN,
		Block::LEVER,
		Block::STONE_PRESSURE_PLATE,
		Block::WOODEN_PRESSURE_PLATE,
		Block::UNLIT_REDSTONE_TORCH,
		Block::LIT_REDSTONE_TORCH,
		Block::STONE_BUTTON,
		-16*Block::SNOW-0,
		-16*Block::SNOW-8,
		Block::REEDS_BLOCK,
		Block::PORTAL,
		Block::UNPOWERED_REPEATER,
		Block::POWERED_REPEATER,
		Block::PUMPKIN_STEM,
		Block::MELON_STEM,
		Block::VINE,
		Block::NETHER_WART_PLANT,
		Block::END_PORTAL,
		Block::TRIPWIRE_HOOK,
		Block::TRIPWIRE,
		Block::CARROTS,
		Block::POTATOES,
		Block::WOODEN_BUTTON,
		Block::LIGHT_WEIGHTED_PRESSURE_PLATE,
		Block::HEAVY_WEIGHTED_PRESSURE_PLATE,
		Block::UNPOWERED_COMPARATOR,
		Block::POWERED_COMPARATOR,
		Block::ACTIVATOR_RAIL,
		Block::IRON_TRAPDOOR,
		Block::CARPET,
		Block::DOUBLE_PLANT,
		Block::STANDING_BANNER,
		Block::WALL_BANNER
	];

	public static function canPassThrough(int $id, ?int $data = null) : bool{
		if($data == null) return in_array($id, self::$canPassThrough);
		return in_array(-16*$id-$data, self::$canPassThrough) || in_array($id, self::$canPassThrough);
	}

	public static $isNaturalTerrainBlock = [
		Block::STONE,
		Block::GRASS,
		Block::DIRT,
		Block::BEDROCK,
		Block::SAND,
		Block::GRAVEL,
		Block::CLAY_BLOCK,
		Block::MYCELIUM,
		Block::PACKED_ICE,
		Block::STAINED_CLAY,

        // hell
		Block::NETHERRACK,
		Block::SOUL_SAND,
		Block::GLOWSTONE,
		Block::QUARTZ_ORE,

        // ores
		Block::COAL_ORE,
		Block::IRON_ORE,
		Block::GOLD_ORE,
		Block::LAPIS_ORE,
		Block::DIAMOND_ORE,
		Block::REDSTONE_ORE,
		Block::GLOWING_REDSTONE_ORE,
		Block::EMERALD_ORE
	];

	public static function isNaturalTerrainBlock(int $id, ?int $data = null) : bool{
		if($data == null) return in_array($id, self::$isNaturalTerrainBlock);
		return in_array(-16*$id-$data, self::$isNaturalTerrainBlock) || in_array($id, self::$isNaturalTerrainBlock);
	}

	public static $isTranslucent = [
		Block::AIR,
		Block::SAPLING,
		Block::WATER,
		Block::STILL_WATER,
		Block::LEAVES,
		Block::GLASS,
		Block::BED_BLOCK,
		Block::POWERED_RAIL,
		Block::DETECTOR_RAIL,
		Block::COBWEB,
		Block::GLASS_PANE,
		Block::DEAD_BUSH,
		Block::PISTONARMCOLLISION,
		Block::YELLOW_FLOWER,
		Block::RED_FLOWER,
		Block::BROWN_MUSHROOM_BLOCK,
		Block::RED_MUSHROOM_BLOCK,
		Block::TORCH,
		Block::FIRE,
		Block::MOB_SPAWNER,
		Block::OAK_STAIRS,
		Block::CHEST,
		Block::REDSTONE_WIRE,
		Block::WHEAT_BLOCK,
		Block::SIGN_POST,
		Block::OAK_DOOR_BLOCK,
		Block::LADDER,
		Block::RAIL,
		Block::COBBLESTONE_STAIRS,
		Block::WALL_SIGN,
		Block::LEVER,
		Block::STONE_PRESSURE_PLATE,
		Block::IRON_DOOR_BLOCK,
		Block::WOODEN_PRESSURE_PLATE,
		Block::UNLIT_REDSTONE_TORCH,
		Block::LIT_REDSTONE_TORCH,
		Block::STONE_BUTTON,
		Block::SNOW,
		Block::ICE,
		Block::CACTUS,
		Block::REEDS_BLOCK,
		Block::FENCE,
		Block::PORTAL,
		Block::CAKE_BLOCK,
		Block::UNPOWERED_REPEATER,
		Block::POWERED_REPEATER,
		Block::TRAPDOOR,
		Block::IRON_BARS,
		Block::PUMPKIN_STEM,
		Block::MELON_STEM,
		Block::VINE,
		Block::FENCE_GATE,
		Block::BRICK_STAIRS,
		Block::STONE_BRICK_STAIRS,
		Block::LILY_PAD,
		Block::NETHER_BRICK_FENCE,
		Block::NETHER_BRICK_STAIRS,
		Block::NETHER_WART_PLANT,
		Block::ENCHANTING_TABLE,
		Block::BREWING_STAND_BLOCK,
		Block::CAULDRON_BLOCK,
		Block::WOODEN_SLAB,
		Block::COCOA,
		Block::SANDSTONE_STAIRS,
		Block::ENDER_CHEST,
		Block::TRIPWIRE_HOOK,
		Block::TRIPWIRE,
		Block::SPRUCE_STAIRS,
		Block::BIRCH_STAIRS,
		Block::JUNGLE_STAIRS,
		Block::COBBLESTONE_WALL,
		Block::FLOWER_POT_BLOCK,
		Block::CARROTS,
		Block::POTATOES,
		Block::WOODEN_BUTTON,
		Block::SKULL_BLOCK,
		Block::ANVIL,
		Block::TRAPPED_CHEST,
		Block::LIGHT_WEIGHTED_PRESSURE_PLATE,
		Block::HEAVY_WEIGHTED_PRESSURE_PLATE,
		Block::UNPOWERED_COMPARATOR,
		Block::POWERED_COMPARATOR,
		Block::DAYLIGHT_SENSOR,
		Block::HOPPER_BLOCK,
		Block::QUARTZ_STAIRS,
		Block::ACTIVATOR_RAIL,
		Block::IRON_TRAPDOOR,
		Block::CARPET,
		Block::DOUBLE_PLANT,
		Block::STANDING_BANNER,
		Block::WALL_BANNER,
		Block::DAYLIGHT_DETECTOR_INVERTED,
		Block::RED_SANDSTONE_STAIRS,
		Block::STONE_SLAB2,
		Block::SPRUCE_FENCE_GATE,
		Block::BIRCH_FENCE_GATE,
		Block::JUNGLE_FENCE_GATE,
		Block::DARK_OAK_FENCE_GATE,
		Block::ACACIA_FENCE_GATE,
		//Block::SPRUCE_FENCE,
		//Block::BIRCH_FENCE,
		//Block::JUNGLE_FENCE,
		//Block::DARK_OAK_FENCE,
		//Block::ACACIA_FENCE,
		Block::SPRUCE_DOOR_BLOCK,
		Block::BIRCH_DOOR_BLOCK,
		Block::JUNGLE_DOOR_BLOCK,
		Block::ACACIA_DOOR_BLOCK,
		Block::DARK_OAK_DOOR_BLOCK
	];

	public static function isTranslucent(int $id) : bool{
		return in_array($id, self::$isTranslucent);
	}
}